server.port=${PORT:8080}

# 🗄️ Ligação à Base de Dados PostgreSQL (Docker)
spring.datasource.url=jdbc:postgresql://localhost:5433/notification_db
spring.datasource.username=admin
spring.datasource.password=admin_password123
spring.datasource.driver-class-name=org.postgresql.Driver

# 🛠️ Configurações do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 🐇 Ligação ao RabbitMQ (Docker)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Actuator / Health
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized

# Providers (simulação)
notification.providers.push.simulated-delay-ms=500

# 📧 SMTP Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=longorenato34@gmail.com
spring.mail.password=hgeodspizcfrrcde
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
notification.email.from=longorenato34@gmail.com

# 🔐 Segurança - API Key
api.security.key=unilabs-secret-key-2026

# 📱 Vonage SMS
vonage.api-key=09db168c
vonage.api-secret=2K%A2xmGOlUvJKDg89p^kG$H
vonage.from-name=Unilabs

# 🔥 Firebase Push
firebase.service-account=firebase-service-account.json
